deepleng:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
  # Publish all joint states -----------------------------------
  yaw_controller:
    type: effort_controllers/JointPositionController
    joint: yaw_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}

  pitch_controller:
    type: effort_controllers/JointPositionController
    joint: pitch_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}
